### ISSUE TITLE
Generate HTML in wrong folder

### ISSUE THREAD

**Issue by isylhdin** [Mogztter/asciidoctor-web-pdf#584] opened 2021-12-29 14:58 UTC
I'm trying to generate a pdf from my `.adoc` file with the following commands : 

```
asciidoctor-pdf doc/index.adoc -o dist/doc.pdf
asciidoctor-pdf -D dist doc/index.adoc
```

It produces a `doc.pdf` file in the `dist `folder
But it also produces a `doc.html` file in the `doc `folder too. 

Am I missing something or is it a bug ?
Thx

**Comment by Mogztter** [comment] 2021-12-30 18:45
The HTML file is a *temporary* file or more precisely an intermediate file in order to produce a PDF. 
The destination folder should contain the PDF file. Currently, the HTML file is always generated in the "current" directory.

The problem is that the HTML file might use relative paths, so if we don't generate the HTML file in the "current" directory the browser won't properly resolve these paths.
I have yet to find a solution 😓 

Related issue: https://github.com/Mogztter/asciidoctor-web-pdf/issues/130

**Comment by isylhdin** [comment] 2022-01-04 08:12
Ok, I've added to my script :

`asciidoctor-pdf doc/index.adoc -o dist/doc.pdf && del-cli doc/doc.html`

in order to delete this temporary file

**Comment by Mogztter** [comment] 2022-01-12 10:17
Closing as this is a duplicate of #130

**Closed by Mogztter** 2022-01-12 10:17 UTC
