### ISSUE TITLE
npm wants to replace existing asciidoctor-pdf ?!

### ISSUE THREAD

**Issue by kwoot** [Mogztter/asciidoctor-web-pdf#383] opened 2021-01-14 13:30 UTC
When trying to install this project it seem to want to replace the existing asciidoctor-pdf.

Please assign a unique name to your own executable.

```
sudo npm i -g @asciidoctor/core asciidoctor-pdf
[sudo] wachtwoord voor jeroen: 
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
/usr/local/bin/asciidoctor-web-pdf -> /usr/local/lib/node_modules/asciidoctor-pdf/bin/asciidoctor-web-pdf
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/asciidoctor-pdf/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/asciidoctor-pdf/bin/asciidoctor-pdf
npm ERR! dest /usr/local/bin/asciidoctor-pdf
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/asciidoctor-pdf/bin/asciidoctor-pdf' -> '/usr/local/bin/asciidoctor-pdf'
npm ERR! File exists: /usr/local/bin/asciidoctor-pdf
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

```

**Comment by Mogztter** [comment] 2021-01-14 13:48
This is a duplicate of https://github.com/Mogztter/asciidoctor-web-pdf/issues/286
I would recommend to use `nvm` (or similar) to install it in your user space (and not in the system space using `sudo`).

You can also install Asciidoctor Web PDF locally in a project directory: https://github.com/Mogztter/asciidoctor-web-pdf#install-in-a-project-directory-alternative-install

Similarly, you should use `rvm` (or similar) to install Asciidoctor PDF in your user space then you can use both `asciidoctor-pdf` and `asciidoctor-web-pdf` command-line.

**Comment by Mogztter** [comment] 2021-02-28 09:42
Closing, let's continue discussion: https://github.com/Mogztter/asciidoctor-web-pdf/issues/286

**Closed by Mogztter** 2021-02-28 09:42 UTC
Labels: :space_invader: duplicate
