### ISSUE TITLE
umlaut breaking PDF outline

### ISSUE THREAD

**Issue by glb94** [Mogztter/asciidoctor-web-pdf#467] opened 2021-04-25 19:33 UTC
When I run a document with umlaut (like áéíóú) in Section Titles I get this message for each entry

Unable to find destination *Destination Name* while generating PDF outline! This 
likely happened because an anchor link contained an umlaut (https://bugs.chromium.org/p/chromium/issues/detail?id=985254).

On the Chronium page this problem shows as fixed

**Comment by Mogztter** [comment] 2021-04-26 19:51
Hello @glb94 

This is actually a duplicate of https://github.com/Mogztter/asciidoctor-web-pdf/issues/340.
This issue was fixed in https://github.com/Mogztter/asciidoctor-web-pdf/commit/4daae8e0c30e5cf95ddee2514150a5d7263cf12f and will be available in the next release (not planned yet).

If you want to confirm that this issue is resolved, you can clone the repository and run `./bin/asciidoctor-web-pdf` from the master branch.

**Closed by Mogztter** 2021-04-26 19:51 UTC
Labels: :space_invader: duplicate
