### ISSUE TITLE
windows 10 installation error

### ISSUE THREAD

**Issue by pinggit** [Mogztter/asciidoctor-web-pdf#247] opened 2020-06-01 20:58 UTC
it doesn't work in windows

```
PS C:\Users\pings> npm i -g @asciidoctor/core asciidoctor-pdf
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
```

**Comment by Mogztter** [comment] 2020-06-01 21:07
It might be related to your environment, here's what I get:


```console
C:\Users\ggrossetie>nvm use 12.17.0
node v12.17.0 (64-bit) is not installed.
```
```console
C:\Users\ggrossetie>nvm install 12.17.0
Downloading node.js version 12.17.0 (64-bit)...
Complete
Creating C:\Users\ggrossetie\AppData\Roaming\nvm\temp

Downloading npm version 6.14.4... Complete
Installing npm v6.14.4...

Installation complete. If you want to use this version, type

nvm use 12.17.0
```
```console
C:\Users\ggrossetie>nvm use 12.17.0
Now using node v12.17.0 (64-bit)
```
```console
C:\Users\ggrossetie>npm i -g @asciidoctor/core asciidoctor-pdf
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
C:\Program Files\nodejs\asciidoctor-pdf -> C:\Program Files\nodejs\node_modules\asciidoctor-pdf\bin\asciidoctor-pdf

> puppeteer@2.0.0 install C:\Program Files\nodejs\node_modules\asciidoctor-pdf\node_modules\puppeteer
> node install.js

Downloading Chromium r706915 - 146 Mb [====================] 100% 0.0s
Chromium downloaded to C:\Users\ggrossetie\AppData\Roaming\nvm\v12.17.0\node_modules\asciidoctor-pdf\node_modules\puppeteer\.local-chromium\win64-706915

> core-js@2.6.11 postinstall C:\Program Files\nodejs\node_modules\asciidoctor-pdf\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules\asciidoctor-pdf\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ asciidoctor-pdf@1.0.0-alpha.7
+ @asciidoctor/core@2.2.0
added 273 packages from 177 contributors in 36.903s
```
```console
C:\Users\ggrossetie>"c:\Program Files\nodejs\asciidoctor-pdf.cmd" --version
Asciidoctor PDF 1.0.0-alpha.7 using Asciidoctor.js 2.2.0 (Asciidoctor 2.0.10) [https://asciidoctor.org]
Runtime Environment (node v12.17.0 on win32)
CLI version 3.2.0
```

**Comment by pinggit** [comment] 2020-06-02 02:31
I was using 12.13.0

```
PS C:\Users\pings> nvm install 12.13.0
Downloading node.js version 12.13.0 (64-bit)...
Complete
Creating C:\Users\pings\AppData\Roaming\nvm\temp

Downloading npm version 6.12.0... Complete
Installing npm v6.12.0...

Installation complete. If you want to use this version, type

nvm use 12.13.0
PS C:\Users\pings> nvm use 12.13.0
Now using node v12.13.0 (64-bit)
PS C:\Users\pings> npm
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
```

let me try 12.17.0 and see...

**Comment by pinggit** [comment] 2020-06-02 02:38
same thing...

```
PS C:\Users\pings> nvm install 12.17.0
Downloading node.js version 12.17.0 (64-bit)...
Complete
Creating C:\Users\pings\AppData\Roaming\nvm\temp

Downloading npm version 6.14.4... Complete
Installing npm v6.14.4...

Installation complete. If you want to use this version, type

nvm use 12.17.0
PS C:\Users\pings>
PS C:\Users\pings> nvm use 12.17.0
Now using node v12.17.0 (64-bit)
PS C:\Users\pings>
PS C:\Users\pings> npm i -g @asciidoctor/core asciidoctor-pdf
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
PS C:\Users\pings>
```

**Comment by Mogztter** [comment] 2020-06-02 06:39
I don't think the error is related to the `asciidoctor-pdf` package. Can you try to install another package?

**Comment by pinggit** [comment] 2020-06-02 13:30
not related to asciidoctor-pdf. actually it looks like npm command itself was not installed correctly.

```
PS C:\Users\pings> npm
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
```

**Comment by Mogztter** [comment] 2020-06-02 14:04
I would recommend a clean (re)install of Node and/or nvm and try to avoid using sudo at all cost. Most of the time that's the root cause of many issues. And also try to install in your "user space" when using WSL or Linux.

**Comment by Mogztter** [comment] 2020-06-08 08:54
Closing in favor of: https://github.com/Mogztter/asciidoctor-web-pdf/issues/244

**Closed by Mogztter** 2020-06-08 08:54 UTC
Labels: 🆘 support
